---
- hosts: all
  become: yes
  tasks:
    # required to rsyslog can discover hostname
    - name: create /etc/hosts
      copy:
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        content: |
          # Managed by Ansible

          127.0.0.1 {{ inventory_hostname.split(".")[0] }} {{ inventory_hostname }} localhost

          # The following lines are desirable for IPv6 capable hosts
          ::1 ip6-localhost ip6-loopback
          fe00::0 ip6-localnet
          ff00::0 ip6-mcastprefix
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters
          ff02::3 ip6-allhosts
