---
- hosts: all
  become: yes
  tasks:
    - name: install rsyslog
      apt:
        name: rsyslog
        state: present
        force_apt_get: yes

    - name: write udp module configuration
      copy:
        dest: /etc/rsyslog.d/10-docker.conf
        owner: root
        group: root
        mode: 0644
        content: |
          module(load="imudp")
          input(type="imudp" address="127.0.0.1" port="514")
          if $programname == "docker" then /var/log/containers.log
          & stop
      notify: restart rsyslog

    - name: start and enable rsyslog
      systemd:
        name: rsyslog.service
        state: started
        enabled: yes

    - name: write logrotate configuration
      copy:
        owner: root
        group: root
        mode: 0644
        dest: /etc/logrotate.d/rsyslog
        content: |
          /var/log/syslog
          /var/log/containers.log
          {
            rotate 7
            daily
            missingok
            notifempty
            delaycompress
            compress
            postrotate
              /usr/lib/rsyslog/rsyslog-rotate
            endscript
          }

          /var/log/mail.info
          /var/log/mail.warn
          /var/log/mail.err
          /var/log/mail.log
          /var/log/daemon.log
          /var/log/kern.log
          /var/log/auth.log
          /var/log/user.log
          /var/log/lpr.log
          /var/log/cron.log
          /var/log/debug
          /var/log/messages
          {
            rotate 4
            weekly
            missingok
            notifempty
            compress
            delaycompress
            sharedscripts
            postrotate
              /usr/lib/rsyslog/rsyslog-rotate
            endscript
          }
  handlers:
    - name: restart rsyslog
      systemd:
        name: rsyslog.service
        state: restarted
